# Generated by Django 5.2.14 on 2026-05-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_dailyauditlog'),
        ('shop', '0006_order_idempotency_key_product_version_and_more'),
    ]

    operations = [
    ]
